package Actions;

public enum Action {
	LOG_IN, LOGIN_FIELD, PASS_FIELD,

	SESSION_ID,

	BALANCE, WITHDRAWAL, PAY_BILL, ADD_MONEY, ADD_PHONE_MONEY,
	CONTACT_LIST, EXIT, REGULAR_PAYMENT, ACTION, GET_CONTACTS, WITHDRAWAL_SUM, GET_BALANCE,

	ERROR_CODE, ERROR_NO_USER, ERROR_NOT_MATCHES, ERROR_SETTING_SESSION, ERROE_NO_MONEY
}